#' Predict from kernel regression model
#'
#' Estimate response values using a kernel regression model.  This method
#' gets called implicitly in the \code{predict.fda} method when the
#' fda model is generated by the \code{kernel_fda} method. It is not
#' intended to be used outside of that context.
#'
#' @param object kernel regression model object.
#' @param newdata matrix containing new predictor data.  If not provided,
#' training data will be used.
#' @param ... additional arguments to pass to kernel_regression (not used).
#'
#' @return matrix of predicted values
#' @seealso \code{\link{kernel_reg_model}}
#' @export
predict.kernel_regression <- function(object, newdata, ...) {
    if (missing(newdata)) {
        if (is.null(object$fitted.values)) {
            kernel_matrix <- kernlab::kernelMatrix(kernel = object$kernel_fn,
                x = as.matrix(object$x))
            alpha <- solve(kernel_matrix + diag(object$lambda,
                nrow = nrow(kernel_matrix)), object$y)
            y_hat <- kernel_matrix %*% alpha
            return(y_hat)
        } else {
            return(object$fitted.values)
        }
    } else {
        kernel_matrix <- kernlab::kernelMatrix(object$kernel_fn,
            newdata, as.matrix(object$x))
        alpha <- object$alpha
        return(kernel_matrix %*% alpha)
    }
}

#' Predict from linear regression model
#'
#' Estimate response values using a linear regression model.  This method
#' gets called implicitly in the \code{predict.fda} method when the
#' fda model is generated by the \code{linear_fda} method. It is not
#' intended to be used outside of that context.
#'
#' @param object linear regression model object.
#' @param newdata matrix containing new predictor data.  If not provided,
#' training data will be used.
#' @param ... additional arguments to pass to kernel_regression (not used).
#'
#' @return matrix of predicted values
#' @seealso \code{\link{linear_reg_model}}
#' @rdname predict.linear_regression
#' @export
predict.linear_regression <- function(object, newdata,...) {
    if (missing(newdata)) {
        if (is.null(object$fitted.values)) {
            return(object$x %*% object$beta)
        } else {
            return(object$fitted.values)
        }
    } else {
        return(newdata %*% object$beta)
    }
}